# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glfw_config = debug
  game_engine_config = debug

else ifeq ($(config),release)
  glfw_config = release
  game_engine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glfw game_engine

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: glfw

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/glfw -f Makefile config=$(glfw_config)
endif

game_engine: glfw
ifneq (,$(game_engine_config))
	@echo "==== Building game_engine ($(game_engine_config)) ===="
	@${MAKE} --no-print-directory -C . -f game_engine.make config=$(game_engine_config)
endif

clean:
	@${MAKE} --no-print-directory -C dependencies/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C . -f game_engine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glfw"
	@echo "   game_engine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"