#pragma once

#include <unordered_map>
#include <set>
#include <vector>
#include <array>
#include <string>
#include <bit>
#include <algorithm>
#include <memory>
#include <iostream>
#include <fstream>
#include <limits>
#include <optional>
#include <chrono>
#include <stdexcept>
#include <cassert>
#include <cstring>
#include <cstdlib>
#include <cstdint>